### ISSUE TITLE
Does not appear to install with provided instructions

### ISSUE THREAD

**Issue by davidfstr** [whitequark/sublime-better-ocaml#3]
Repro Steps:
- Install latest Sublime Text 3 (build 3083) on OS X 10.9.5 in a fresh VM.
- Install Package Control using instructions provided on its website.
- Command-Shift-P > Package Control: Install Package > OCaml.
- Command-Shift-P > Package Control: List Packages.

Expected Results:
- OCaml listed as an installed package.

Actual Results:
- Only "Package Control" listed as an installed package.

**Comment by whitequark** [comment]
Yes, I think Package Control team mentioned something like that. It might be that sublime-better-ocaml can not be installed by Package Control anymore. Try cloning it directly instead.

**Comment by davidfstr** [comment]
> Try cloning it directly instead.

Will try to do that by the end of this upcoming weekend. Busy times at work.

**Comment by davidfstr** [comment]
I did a git clone of the repository to my packages folder, which appears to have fixed the issue.

```
cd /Users/me/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
git clone git@github.com:whitequark/sublime-better-ocaml.git
```

I think it works now because the "inherit!" keyword is highlighted, which you specifically mention in your README.

If it is in fact the case that installation no longer works with Package Control, I'd recommend updating your README.

**Comment by whitequark** [comment]
Alright, it looks like Package Control broke the installation of packages like this. README updated.
